-- Legacy pointer.
-- The production RLS source of truth is:
-- supabase/migrations/20260612141000_rls_professional_policies.sql
--
-- Keep this file only so older notes that reference supabase/security_rls.sql
-- do not point to stale policies. Do not run this file as the production RLS
-- migration.
